# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [commit, manual]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: detect-private-key
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace
        types: [python]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check
        args: []
        require_serial: true
        language: system
        types: [python]
        exclude: ^tests/
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        language: system
        types: [python]
  - repo:  https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: false
      - id: poetry-lock
        name: poetry lock check
        entry: poetry lock
        args: [--check]
        language: system
        pass_filenames: false
  - repo:  https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        exclude: ^tests/
