name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Check large files
        uses: ppremk/lfs-warning@v3.3
        with:
          filesizelimit: 10MB # so we can sync to HF Spaces
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "alvaroalon2"
          SPACE_NAME: "LinguAIcoach"
        run: git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
      
      - name: Add HF model card
        run: echo $(cat model_card.md) | cat - README.md > temp && mv temp README.md

      - name: Update HF README
        env:
            HF_TOKEN: ${{ secrets.HF_TOKEN }}
            HF_USERNAME: "alvaroalon2"
            SPACE_NAME: "LinguAIcoach"
        run: git add README.md && git commit -m "Update HF README" && git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
