name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Check large files
        uses: ppremk/lfs-warning@v3.3
        with:
          filesizelimit: 10MB # so we can sync to HF Spaces
      
      - name: Add HF model card
        run: |
          echo '---
          title: LinguAIcoach
          emoji: 💬
          colorFrom: blue
          colorTo: red
          sdk: streamlit
          sdk_version: 1.31.1
          python_version: 3.12
          app_file: src/main.py
          pinned: true
          tags: [academic, english, learning, gpt, multimodal, whisper, gpt4-vision, dall-e, chatbot]
          license: cc-by-nd-4.0
          ---' | cat - README.md > temp && mv temp README.md

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "alvaroalon2"
          SPACE_NAME: "LinguAIcoach"
        run: git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
